security:

    encoders:
        App\Entity\User: sha512

    providers:
        user_service:
            entity: { class: App\Entity\User, property: username }

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        resources:
            pattern:  ^/resources
            security: false

        main:
            pattern:  ^/
            anonymous: true
            provider: user_service
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
