vich_uploader:
    db_driver: orm

    mappings:
        books:
            uri_prefix: /userfiles/books
            upload_destination: '%kernel.project_dir%/public/userfiles/books'
        videos:
            uri_prefix: /userfiles/videos
            upload_destination: '%kernel.project_dir%/public/userfiles/videos'
